apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: app
          image: rodrigoengelberg/docker-conversao-temperatura:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort
